
function Menu() {
  return (
    <>
      <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3">
            <div class="container"><div class="nav-brand">
                <p class="site-title m-0"><a href="https://www.mobinius.com/" rel="home"><img src="https://www.mobinius.com/wp-content/themes/mobinius/assets/images/mobinius-logo.svg" style={{width:'180px'}}/></a></p>						
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarSupportedContent" class="collapse navbar-collapse">
                <nav id="ubermenu-main-2-header-menu-2" class="ubermenu ubermenu-nojs ubermenu-main ubermenu-menu-2 ubermenu-loc-header-menu ubermenu-responsive ubermenu-responsive-single-column ubermenu-responsive-single-column-subs ubermenu-responsive-default ubermenu-responsive-nocollapse ubermenu-horizontal ubermenu-transition-fade ubermenu-trigger-hover_intent ubermenu-skin-none  ubermenu-bar-align-full ubermenu-items-align-auto ubermenu-bound ubermenu-sub-indicators ubermenu-retractors-responsive ubermenu-submenu-indicator-closes">
                    <ul id="ubermenu-nav-main-2-header-menu" class="ubermenu-nav" data-title="Mobinius Header">
                        <li id="menu-item-220" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-220 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/about-us" tabIndex="0"><span class="ubermenu-target-title ubermenu-target-text">About</span></a></li>
                        <li id="menu-item-9" class="arrow-menu-link ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-9 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-mega" ><span class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" tabIndex="0"><span class="ubermenu-target-title ubermenu-target-text">Service</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></span>
                            <ul  class="ubermenu-submenu ubermenu-submenu-id-9 ubermenu-submenu-type-auto ubermenu-submenu-type-mega ubermenu-submenu-drop ubermenu-submenu-align-full_width"  >
                                <li id="menu-item-15882" class="ubermenu-item ubermenu-tabs ubermenu-item-15882 ubermenu-item-level-1 ubermenu-column ubermenu-column-full ubermenu-tab-layout-left ubermenu-tabs-show-default ubermenu-tabs-show-current">
                                    <ul  class="ubermenu-tabs-group ubermenu-column ubermenu-column-1-4 ubermenu-submenu ubermenu-submenu-id-15882 ubermenu-submenu-type-auto ubermenu-submenu-type-tabs-group"  >
                                        <li id="menu-item-16889" class="ubermenu-tab mega-menu-column ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16889 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Engineering</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-16889 ubermenu-submenu-type-tab-content-panel"  >
                                                <li id="menu-item-16890" class="tabinner-title-menu ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16890 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Front End</span></a>
                                                    <ul  class="ubermenu-submenu ubermenu-submenu-id-16890 ubermenu-submenu-type-auto ubermenu-submenu-type-stack"  >
                                                        <li id="menu-item-15877" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15877 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/javascript-development-company"><span class="ubermenu-target-title ubermenu-target-text">JavaScript</span></a></li>
                                                        <li id="menu-item-15876" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15876 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/angularjs-development-company"><span class="ubermenu-target-title ubermenu-target-text">Angular</span></a></li>
                                                        <li id="menu-item-15878" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15878 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/reactjs-development-company"><span class="ubermenu-target-title ubermenu-target-text">React JS</span></a></li>
                                                        <li id="menu-item-16631" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16631 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/react-native-app-development-company"><span class="ubermenu-target-title ubermenu-target-text">React Native</span></a></li>
                                                        <li id="menu-item-16630" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16630 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/vuejs-development-company"><span class="ubermenu-target-title ubermenu-target-text">Vue JS</span></a></li>
                                                        <li id="menu-item-18525" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-18525 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/ionic-development-company"><span class="ubermenu-target-title ubermenu-target-text">Ionic</span></a></li>
                                                    </ul>
                                                </li>
                                                <li id="menu-item-16891" class="tabinner-title-menu ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16891 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Back End</span></a>
                                                    <ul  class="ubermenu-submenu ubermenu-submenu-id-16891 ubermenu-submenu-type-auto ubermenu-submenu-type-stack"  >
                                                        <li id="menu-item-15879" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15879 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/nodejs-development-company"><span class="ubermenu-target-title ubermenu-target-text">Node JS</span></a></li>
                                                        <li id="menu-item-16626" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16626 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/python-development-company"><span class="ubermenu-target-title ubermenu-target-text">Python</span></a></li>
                                                        <li id="menu-item-15880" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15880 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/golang-development-company"><span class="ubermenu-target-title ubermenu-target-text">Golang</span></a></li>
                                                        <li id="menu-item-15924" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15924 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/kotlin-development-company"><span class="ubermenu-target-title ubermenu-target-text">Kotlin</span></a></li>
                                                        <li id="menu-item-16775" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16775 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/dot-net-development-company"><span class="ubermenu-target-title ubermenu-target-text">Dot Net</span></a></li>
                                                    </ul>
                                                </li>
                                                <li id="menu-item-16892" class="tabinner-title-menu ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16892 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Full Stack</span></a>
                                                    <ul  class="ubermenu-submenu ubermenu-submenu-id-16892 ubermenu-submenu-type-auto ubermenu-submenu-type-stack"  >
                                                        <li id="menu-item-15925" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15925 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/mean-stack-development-company"><span class="ubermenu-target-title ubermenu-target-text">MEAN Stack</span></a></li>
                                                        <li id="menu-item-16962" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16962 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/mern-stack-development-company"><span class="ubermenu-target-title ubermenu-target-text">MERN Stack</span></a></li>
                                                        <li id="menu-item-18235" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-18235 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/database"><span class="ubermenu-target-title ubermenu-target-text">Database</span></a></li>
                                                    </ul>
                                                </li>
                                                <li id="menu-item-18236" class="tabinner-title-menu ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-18236 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Devops</span></a>
                                                    <ul  class="ubermenu-submenu ubermenu-submenu-id-18236 ubermenu-submenu-type-auto ubermenu-submenu-type-stack"  >
                                                        <li id="menu-item-22395" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-22395 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/devops-development-company"><span class="ubermenu-target-title ubermenu-target-text">DevOps</span></a></li>
                                                    </ul>
                                                </li>
                                                <li id="menu-item-18238" class="tabinner-title-menu ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-18238 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-stack" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">QA</span></a>
                                                    <ul  class="ubermenu-submenu ubermenu-submenu-id-18238 ubermenu-submenu-type-auto ubermenu-submenu-type-stack"  >
                                                        <li id="menu-item-18520" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-18520 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-4 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/engineering/automation-testing-services-with-selenium"><span class="ubermenu-target-title ubermenu-target-text">QA &#038; Automation</span></a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                        <li id="menu-item-15885" class="ubermenu-tab ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-15885 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#Design"><span class="ubermenu-target-title ubermenu-target-text">Design</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-15885 ubermenu-submenu-type-tab-content-panel"  >
                                                <li id="menu-item-16874" class="ubermenu-item ubermenu-tabs ubermenu-item-16874 ubermenu-item-level-3 ubermenu-column ubermenu-column-full ubermenu-tab-layout-left ubermenu-tabs-show-default ubermenu-tabs-show-current">
                                                    <ul  class="ubermenu-tabs-group ubermenu-column ubermenu-column-1-4 ubermenu-submenu ubermenu-submenu-id-16874 ubermenu-submenu-type-auto ubermenu-submenu-type-tabs-group"  >
                                                        <li id="menu-item-16869" class="ubermenu-tab d-none ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16869 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">User Research</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-16869 ubermenu-submenu-type-tab-content-panel"  >
                                                                <li id="menu-item-16873" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-16873 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-5 ubermenu-column ubermenu-column-full" >
                                                                    <div class="ubermenu-content-block ubermenu-custom-content ubermenu-custom-content-padded">
                                                                        <div class="row m-0">
                                                                            <div class="col-3 pl-0 pt-2">
                                                                                {/* <img src="/wp-content/uploads/2020/02/clock-icon-img.png"/> */}
                                                                            </div>
                                                                            <div class="col-9 p-0" style={{fontSize: '12px',  lineHeight: '18px'}}>As a UX consultant, our first step is always about gaining understanding &amp; knowledge. We dig deep to know everything possible that will help us craft a better solution.</div>
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li id="menu-item-16870" class="ubermenu-tab d-none ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-16870 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">User Experience</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-16870 ubermenu-submenu-type-tab-content-panel"  >
                                                                <li id="menu-item-16887" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-16887 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-5 ubermenu-column ubermenu-column-full" >
                                                                    <div class="ubermenu-content-block ubermenu-custom-content ubermenu-custom-content-padded">
                                                                        <div class="row m-0">
                                                                            <div class="col-3 pl-0 pt-2">
                                                                                {/* <img src="/wp-content/uploads/2020/02/clock-icon-img.png"/> */}
                                                                            </div>
                                                                            <div class="col-9 p-0" style={{fontSize: '12px', lineHeight: '18px'}}>UX Experience As a UX consultant, our first step is always about gaining understanding &amp; knowledge. We dig deep to know everything possible that will help us craft a better solution.</div>
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li id="menu-item-18934" class="ubermenu-tab ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-has-children ubermenu-item-18934 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/design/ui-ux-design"><span class="ubermenu-target-title ubermenu-target-text">User Interface</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-18934 ubermenu-submenu-type-tab-content-panel"  >
                                                                <li id="menu-item-16888" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-16888 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-5 ubermenu-column ubermenu-column-full" >
                                                                    <div class="ubermenu-content-block ubermenu-custom-content ubermenu-custom-content-padded">
                                                                        <div class="row m-0">
                                                                            <div class="col-3 pl-0 pt-2">
                                                                                {/* <img src="/wp-content/uploads/2020/02/clock-icon-img.png"/> */}
                                                                            </div>
                                                                            <div class="col-9 p-0" style={{fontSize: '12px',  lineHeight: '18px'}}>UI Design As a UX consultant, our first step is always about gaining understanding &amp; knowledge. We dig deep to know everything possible that will help us craft a better solution.</div>
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                        <li id="menu-item-15886" class="ubermenu-tab ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-15886 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#innovation"><span class="ubermenu-target-title ubermenu-target-text">Innovation</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-15886 ubermenu-submenu-type-tab-content-panel"  >
                                                <li id="menu-item-16979" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16979 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/cawi"><span class="ubermenu-target-title ubermenu-target-text">CAWI.AI</span></a></li>
                                                <li id="menu-item-16897" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16897 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-1-2" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/cloud-computing-company"><span class="ubermenu-target-title ubermenu-target-text">Cloud Computing</span></a></li>
                                                <li id="menu-item-15928" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15928 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-1-2" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/iot-solutions-development-company"><span class="ubermenu-target-title ubermenu-target-text">IOT</span></a></li>
                                                <li id="menu-item-16898" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16898 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-1-2" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/digital-transformation-company"><span class="ubermenu-target-title ubermenu-target-text">Digital Transformation</span></a></li>
                                                <li id="menu-item-16986" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16986 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/ai-development-company"><span class="ubermenu-target-title ubermenu-target-text">AI</span></a></li>
                                                <li id="menu-item-16965" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16965 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/mobinius-molecules-development-company"><span class="ubermenu-target-title ubermenu-target-text">Mobinius Molecules</span></a></li>
                                                <li id="menu-item-16978" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16978 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/machine-learning-services-and-solutions"><span class="ubermenu-target-title ubermenu-target-text">ML</span></a></li>
                                                <li id="menu-item-16977" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-16977 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/blockchain-development-company"><span class="ubermenu-target-title ubermenu-target-text">Blockchain</span></a></li>
                                                <li id="menu-item-18522" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-18522 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-3 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/innovation/legacy-modernization-services"><span class="ubermenu-target-title ubermenu-target-text">Legacy Modernization</span></a></li>
                                            </ul>
                                        </li>
                                        <li id="menu-item-22025" class="ubermenu-tab ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-22025 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="#"><span class="ubermenu-target-title ubermenu-target-text">Loyalty</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-22025 ubermenu-submenu-type-tab-content-panel"  >
                                                <li id="menu-item-22026" class="ubermenu-item ubermenu-tabs ubermenu-item-22026 ubermenu-item-level-3 ubermenu-column ubermenu-column-full ubermenu-tab-layout-left ubermenu-tabs-show-default ubermenu-tabs-show-current">
                                                    <ul  class="ubermenu-tabs-group ubermenu-column ubermenu-column-1-4 ubermenu-submenu ubermenu-submenu-id-22026 ubermenu-submenu-type-auto ubermenu-submenu-type-tabs-group"  >
                                                        <li id="menu-item-22024" class="ubermenu-tab ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-has-children ubermenu-item-22024 ubermenu-item-auto ubermenu-column ubermenu-column-full ubermenu-has-submenu-drop" data-ubermenu-trigger="mouseover" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/service/loyalty/loyalty-management-solutions"><span class="ubermenu-target-title ubermenu-target-text">Loyalty Offerings</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                                                            <ul  class="ubermenu-tab-content-panel ubermenu-column ubermenu-column-3-4 ubermenu-submenu ubermenu-submenu-id-22024 ubermenu-submenu-type-tab-content-panel"  >
                                                                <li id="menu-item-22027" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-ubermenu-custom ubermenu-item-22027 ubermenu-item-auto ubermenu-item-header ubermenu-item-level-5 ubermenu-column ubermenu-column-auto" >
                                                                    <div class="ubermenu-content-block ubermenu-custom-content ubermenu-custom-content-padded">
                                                                        <div class="row m-0">
                                                                            <div class="col-3 pl-0 pt-2">
                                                                                {/* <img src="/wp-content/uploads/2021/02/loyalty-icon-img.jpg" style={{width: '64px',  float: 'right'}}/> */}
                                                                            </div>
                                                                            <div class="col-9 p-0" style={{fontSize: '12px',  lineHeight: '18px'}}>Loyalty Services is an integral part of the entire customer focus, in any product/service value chain. We offer the top edge solutions in crafting various loyalty offerings </div>
                                                                        </div>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        </li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                        </ul>
                                </li>
                            </ul>
                        </li>
                        <li id="menu-item-11" class="arrow-menu-link ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-has-children ubermenu-item-11 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-flyout" ><span class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" tabIndex="0"><span class="ubermenu-target-title ubermenu-target-text">Insights</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></span>
                            <ul  class="ubermenu-submenu ubermenu-submenu-id-11 ubermenu-submenu-type-flyout ubermenu-submenu-drop ubermenu-submenu-align-left_edge_item"  >
                                <li id="menu-item-15785" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-15785 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-1" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/blogs"><span class="ubermenu-target-title ubermenu-target-text">Blogs</span></a></li>
                                <li id="menu-item-15892" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-15892 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-1" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://mobinius.com/insights/white-papers"><span class="ubermenu-target-title ubermenu-target-text">White Papers</span></a></li>
                                <li id="menu-item-15890" class="ubermenu-item ubermenu-item-type-custom ubermenu-item-object-custom ubermenu-item-15890 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-1" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://mobinius.com/insights/case-studies"><span class="ubermenu-target-title ubermenu-target-text">Case Studies</span></a></li>
                            </ul>
                        </li>
                        <li id="menu-item-44" class="arrow-menu-link ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-has-children ubermenu-item-44 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto ubermenu-has-submenu-drop ubermenu-has-submenu-flyout" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/careers" tabIndex="0"><span class="ubermenu-target-title ubermenu-target-text">Careers</span><i class='ubermenu-sub-indicator fas fa-angle-down'></i></a>
                            <ul  class="ubermenu-submenu ubermenu-submenu-id-44 ubermenu-submenu-type-flyout ubermenu-submenu-drop ubermenu-submenu-align-left_edge_item" >
                                <li id="menu-item-17158" class="ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-17158 ubermenu-item-auto ubermenu-item-normal ubermenu-item-level-1" ><a class="ubermenu-target ubermenu-item-layout-default ubermenu-item-layout-text_only" href="https://www.mobinius.com/culture"><span class="ubermenu-target-title ubermenu-target-text">Culture</span></a></li>
                            </ul>
                        </li>
                        <li id="menu-item-221" class="menu-outline-btn ubermenu-item ubermenu-item-type-post_type ubermenu-item-object-page ubermenu-item-221 ubermenu-item-level-0 ubermenu-column ubermenu-column-auto" ><a class="ubermenu-target ubermenu-target-with-icon ubermenu-item-layout-default ubermenu-item-layout-icon_left" href="https://www.mobinius.com/contact-us" tabIndex="0"><i class="ubermenu-icon far fa-envelope" ></i><span class="ubermenu-target-title ubermenu-target-text">Contact Us</span></a></li>
                    </ul>
                </nav>
            </div>
            </div>
        </nav>
      </header>
    </>
  )
}

export default Menu